### ISSUE TITLE
(epic) basic RH info 

### ISSUE THREAD

**Issue by westonplatter** [westonplatter/fast_arrow#1]
The goal is to setup the basic structure for the API client and fetch basic RH account info.

Basic structure:
- [x] authentication
- [x] MFA authentication
- [x] migrate `token` to `oauth2` bearer token
- [x] basic test suite with a CI

Endpoints to fetch from:
- [x] get user 
- [x] get positions
- [x] get option_positions

**Comment by westonplatter** [comment]
Closing since #41 has been merged to finish out expected features.
