### ISSUE TITLE
(epic) Options Position data

### ISSUE THREAD

**Issue by westonplatter** [westonplatter/fast_arrow#4]
Todos:
-  [x] adjust the greeks to be positive/negative based on type (ie, long/short)
- [x] add Strike Price to resulting position data
- [x] batch request MarketData like the web ui does (rather than n+1 querying the API).
